/**
 * EduCode Studio - Starter Templates & Educational Exercises
 */

var TEMPLATES = {
  'html-basic': {
    name: '🚀 Estructura Básica HTML5',
    html: '<!DOCTYPE html>\n<html lang="es">\n<head>\n  <meta charset="UTF-8">\n  <title>Mi Primera Página Web</title>\n</head>\n<body>\n  <header>\n    <h1>👋 ¡Bienvenidos a mi sitio web!</h1>\n    <p>Esta es mi primera práctica de HTML5 en EduCode Studio.</p>\n  </header>\n\n  <main>\n    <section class="card">\n      <h2>📌 Sobre mí</h2>\n      <p>Soy un estudiante aprendiendo desarrollo web frontend con <strong>HTML, CSS y JS</strong>.</p>\n    </section>\n\n    <section class="card">\n      <h2>🔥 Mis Tecnologías Favoritas:</h2>\n      <ul>\n        <li>HTML5 - Estructura y Contenido</li>\n        <li>CSS3 - Estilos y Animaciones</li>\n        <li>JavaScript - Lógica e Interactividad</li>\n      </ul>\n    </section>\n  </main>\n\n  <footer>\n    <p>&copy; 2026 - Creado con ❤️ en la clase de programación</p>\n  </footer>\n</body>\n</html>',
    css: '/* Estilos generales */\nbody {\n  font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;\n  background-color: #f4f7f6;\n  color: #333333;\n  margin: 0;\n  padding: 20px;\n  line-height: 1.6;\n}\n\nheader {\n  text-align: center;\n  background: #4a90e2;\n  color: white;\n  padding: 24px;\n  border-radius: 12px;\n  margin-bottom: 20px;\n}\n\nheader h1 {\n  margin: 0 0 10px 0;\n}\n\n.card {\n  background: white;\n  padding: 20px;\n  border-radius: 10px;\n  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);\n  margin-bottom: 16px;\n}\n\nul {\n  padding-left: 20px;\n}\n\nli {\n  margin-bottom: 8px;\n  font-weight: 500;\n}\n\nfooter {\n  text-align: center;\n  margin-top: 30px;\n  color: #777;\n  font-size: 0.9em;\n}',
    js: '// Imprimir en la consola virtual\nconsole.log("¡Hola desde JavaScript!");\nconsole.info("Página cargada con éxito. Prueba a editar el código.");'
  },

  'css-card': {
    name: '🎨 Tarjeta Interactiva con CSS',
    html: '<div class="container">\n  <div class="profile-card">\n    <div class="card-header">\n      <div class="avatar">👨‍💻</div>\n    </div>\n    <div class="card-body">\n      <h3>Alex Developer</h3>\n      <p class="role">Estudiante de Programación</p>\n      <p class="bio">Apasionado por el diseño UI/UX y la creación de aplicaciones web interactivas.</p>\n\n      <div class="skills">\n        <span class="tag">HTML5</span>\n        <span class="tag">CSS3</span>\n        <span class="tag">JavaScript</span>\n      </div>\n\n      <button id="btn-like" class="btn-action">❤️ Me gusta (<span>0</span>)</button>\n    </div>\n  </div>\n</div>',
    css: ':root {\n  --primary-color: #6366f1;\n  --secondary-color: #a855f7;\n  --bg-gradient: linear-gradient(135deg, #0f172a, #1e1b4b);\n}\n\nbody {\n  font-family: \'Inter\', sans-serif;\n  background: var(--bg-gradient);\n  min-height: 100vh;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  margin: 0;\n  color: #fff;\n}\n\n.container {\n  padding: 20px;\n}\n\n.profile-card {\n  background: rgba(255, 255, 255, 0.07);\n  backdrop-filter: blur(12px);\n  border: 1px solid rgba(255, 255, 255, 0.15);\n  border-radius: 20px;\n  width: 320px;\n  text-align: center;\n  overflow: hidden;\n  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.4);\n  transition: transform 0.3s ease, box-shadow 0.3s ease;\n}\n\n.profile-card:hover {\n  transform: translateY(-8px);\n  box-shadow: 0 30px 60px rgba(99, 102, 241, 0.3);\n}\n\n.card-header {\n  height: 90px;\n  background: linear-gradient(90deg, var(--primary-color), var(--secondary-color));\n  position: relative;\n}\n\n.avatar {\n  width: 80px;\n  height: 80px;\n  background: #1e293b;\n  border-radius: 50%;\n  font-size: 40px;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  position: absolute;\n  bottom: -40px;\n  left: 50%;\n  transform: translateX(-50%);\n  border: 4px solid #1e293b;\n}\n\n.card-body {\n  padding: 50px 24px 24px;\n}\n\nh3 {\n  margin: 10px 0 4px;\n  font-size: 1.3rem;\n}\n\n.role {\n  color: #a5b4fc;\n  font-size: 0.85rem;\n  margin-bottom: 12px;\n}\n\n.bio {\n  color: #cbd5e1;\n  font-size: 0.9rem;\n  line-height: 1.5;\n  margin-bottom: 20px;\n}\n\n.skills {\n  display: flex;\n  justify-content: center;\n  gap: 8px;\n  margin-bottom: 20px;\n}\n\n.tag {\n  background: rgba(99, 102, 241, 0.2);\n  color: #818cf8;\n  padding: 4px 10px;\n  border-radius: 12px;\n  font-size: 0.75rem;\n  font-weight: 600;\n}\n\n.btn-action {\n  background: linear-gradient(90deg, var(--primary-color), var(--secondary-color));\n  color: white;\n  border: none;\n  padding: 10px 20px;\n  border-radius: 25px;\n  font-weight: 600;\n  cursor: pointer;\n  width: 100%;\n  transition: opacity 0.2s ease;\n}\n\n.btn-action:hover {\n  opacity: 0.9;\n}',
    js: '// Funcionalidad del botón de Me Gusta\nlet likes = 0;\nconst btnLike = document.getElementById(\'btn-like\');\nconst countSpan = btnLike.querySelector(\'span\');\n\nbtnLike.addEventListener(\'click\', () => {\n  likes++;\n  countSpan.textContent = likes;\n  console.log("¡Nuevo Like registrado! Total:", likes);\n});'
  },

  'js-counter': {
    name: '⚡ Contador e Interacción DOM',
    html: '<div class="app-card">\n  <h2>🧮 Contador Interactivo</h2>\n  <div class="display" id="counter">0</div>\n  \n  <div class="buttons">\n    <button id="btn-decrement" class="btn red">- Restar</button>\n    <button id="btn-reset" class="btn gray">↺ Reset</button>\n    <button id="btn-increment" class="btn green">+ Sumar</button>\n  </div>\n\n  <hr>\n\n  <button id="btn-theme" class="btn-theme">🌓 Cambiar Fondo</button>\n</div>',
    css: 'body {\n  font-family: system-ui, sans-serif;\n  background-color: #1e1e2e;\n  color: #cdd6f4;\n  height: 100vh;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  margin: 0;\n  transition: background-color 0.4s ease;\n}\n\nbody.light-mode {\n  background-color: #eff1f5;\n  color: #4c4f69;\n}\n\n.app-card {\n  background: rgba(255, 255, 255, 0.05);\n  border: 1px solid rgba(255, 255, 255, 0.1);\n  padding: 30px;\n  border-radius: 16px;\n  text-align: center;\n  width: 320px;\n  box-shadow: 0 10px 30px rgba(0,0,0,0.3);\n}\n\nbody.light-mode .app-card {\n  background: white;\n  border-color: #ccd0da;\n}\n\n.display {\n  font-size: 4rem;\n  font-weight: bold;\n  margin: 20px 0;\n  color: #89b4fa;\n}\n\n.buttons {\n  display: flex;\n  gap: 10px;\n  justify-content: center;\n}\n\n.btn {\n  padding: 10px 16px;\n  border: none;\n  border-radius: 8px;\n  font-weight: bold;\n  cursor: pointer;\n  transition: transform 0.1s ease;\n}\n\n.btn:active {\n  transform: scale(0.95);\n}\n\n.btn.green { background: #a6e3a1; color: #11111b; }\n.btn.red { background: #f38ba8; color: #11111b; }\n.btn.gray { background: #6c7086; color: #ffffff; }\n\nhr {\n  margin: 24px 0;\n  border: 0;\n  border-top: 1px solid rgba(255,255,255,0.1);\n}\n\n.btn-theme {\n  width: 100%;\n  padding: 10px;\n  background: #cba6f7;\n  color: #11111b;\n  border: none;\n  border-radius: 8px;\n  font-weight: bold;\n  cursor: pointer;\n}',
    js: '// Elementos del DOM\nconst counterDisplay = document.getElementById(\'counter\');\nconst btnIncrement = document.getElementById(\'btn-increment\');\nconst btnDecrement = document.getElementById(\'btn-decrement\');\nconst btnReset = document.getElementById(\'btn-reset\');\nconst btnTheme = document.getElementById(\'btn-theme\');\n\nlet count = 0;\n\nfunction updateDisplay() {\n  counterDisplay.textContent = count;\n  console.log("Valor actual del contador: " + count);\n}\n\nbtnIncrement.addEventListener(\'click\', () => {\n  count++;\n  updateDisplay();\n});\n\nbtnDecrement.addEventListener(\'click\', () => {\n  count--;\n  updateDisplay();\n});\n\nbtnReset.addEventListener(\'click\', () => {\n  count = 0;\n  updateDisplay();\n  console.warn("Contador reiniciado a 0");\n});\n\nbtnTheme.addEventListener(\'click\', () => {\n  document.body.classList.toggle(\'light-mode\');\n  const isLight = document.body.classList.contains(\'light-mode\');\n  console.info("Modo de color cambiado a: " + (isLight ? "Claro" : "Oscuro"));\n});'
  },

  'canvas-animation': {
    name: '🎮 Animación de Canvas 2D',
    html: '<div class="canvas-container">\n  <h2>⚽ Simulación de Pelotas Rebotando</h2>\n  <canvas id="gameCanvas" width="500" height="350"></canvas>\n  <p>Haz clic en el lienzo para agregar más pelotas.</p>\n</div>',
    css: 'body {\n  margin: 0;\n  background: #0f172a;\n  color: #f8fafc;\n  font-family: system-ui, sans-serif;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  height: 100vh;\n}\n\n.canvas-container {\n  text-align: center;\n}\n\nh2 {\n  margin-bottom: 12px;\n  color: #38bdf8;\n}\n\ncanvas {\n  background: #1e293b;\n  border: 2px solid #38bdf8;\n  border-radius: 12px;\n  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.5);\n  cursor: pointer;\n}\n\np {\n  color: #94a3b8;\n  font-size: 0.9rem;\n  margin-top: 8px;\n}',
    js: 'const canvas = document.getElementById(\'gameCanvas\');\nconst ctx = canvas.getContext(\'2d\');\n\nconst balls = [];\n\nclass Ball {\n  constructor(x, y) {\n    this.x = x;\n    this.y = y;\n    this.radius = Math.random() * 15 + 10;\n    this.dx = (Math.random() - 0.5) * 6;\n    this.dy = (Math.random() - 0.5) * 6;\n    this.color = "hsl(" + Math.floor(Math.random() * 360) + ", 80%, 60%)";\n  }\n\n  draw() {\n    ctx.beginPath();\n    ctx.arc(this.x, this.y, this.radius, 0, Math.PI * 2);\n    ctx.fillStyle = this.color;\n    ctx.fill();\n    ctx.closePath();\n  }\n\n  update() {\n    if (this.x + this.radius > canvas.width || this.x - this.radius < 0) {\n      this.dx = -this.dx;\n    }\n    if (this.y + this.radius > canvas.height || this.y - this.radius < 0) {\n      this.dy = -this.dy;\n    }\n    this.x += this.dx;\n    this.y += this.dy;\n    this.draw();\n  }\n}\n\nfor (var i = 0; i < 5; i++) {\n  balls.push(new Ball(canvas.width / 2, canvas.height / 2));\n}\n\nfunction animate() {\n  ctx.clearRect(0, 0, canvas.width, canvas.height);\n  balls.forEach(function(ball) { ball.update(); });\n  requestAnimationFrame(animate);\n}\n\nanimate();\n\ncanvas.addEventListener(\'click\', function(e) {\n  var rect = canvas.getBoundingClientRect();\n  var x = e.clientX - rect.left;\n  var y = e.clientY - rect.top;\n  balls.push(new Ball(x, y));\n  console.log("Pelota agregada en (" + Math.round(x) + ", " + Math.round(y) + "). Total pelotas: " + balls.length);\n});'
  },

  'blank': {
    name: '🧹 Proyecto en Blanco',
    html: '<!DOCTYPE html>\n<html lang="es">\n<head>\n  <meta charset="UTF-8">\n  <title>Mi Proyecto</title>\n</head>\n<body>\n  <h1>Hola Mundo</h1>\n</body>\n</html>',
    css: '/* Escribe tus estilos CSS aquí */\nbody {\n  font-family: sans-serif;\n  padding: 20px;\n}',
    js: '// Escribe tu código JavaScript aquí\nconsole.log("Listo para programar!");'
  }
};
